AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: TransactionProcessing.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: 'Lambda function to handle POST events from SAP CPI'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::523415761587:role/service-role/TransactionProcessing-role-s4n1tmes'
      Events:
        AWSTargetEndpoint:
          Type: Api
          Properties:
            Path: /transaction
            Method: post
      Environment:
        Variables:
          REGION: us-east-1
